name: Build Node.js app on AWS EC2

on:
  push:
    branches: ['master']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run a build command
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: .ansible/main.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [all]
            ${{ secrets.HOST }} address=localhost
          options: |
            -e GITHUB_REPO=${{ github.repository }}
            -e NODE_ENV=production
            -e APP_PATH=/home/app/backend.ecdevstudio.com
            -e DB_HOST=${{ secrets.DB_HOST }}
            -e DB_NAME=${{ secrets.DB_NAME }}
            -e DB_PASS=${{ secrets.DB_PASS }}
            -e DB_USER=${{ secrets.DB_USER }}
